syntax = "proto3";

package raptor.v1;

enum SignalId {
  // reserved
  SIGNAL_ID_UNSPECIFIED = 0;

  SIGNAL_ID_POWERTRAIN_CURRENT = 1;
  SIGNAL_ID_POWERTRAIN_VOLTAGE = 2;
  SIGNAL_ID_BLDC_L1_VOLTAGE = 3;
  SIGNAL_ID_BLDC_L2_VOLTAGE = 4;
  SIGNAL_ID_BLDC_L3_VOLTAGE = 5;

  SIGNAL_ID_BLDC_RPM = 10;
  SIGNAL_ID_THRUST = 11;
  SIGNAL_ID_TORQUE1 = 12;
  SIGNAL_ID_TORQUE2 = 13;

  SIGNAL_ID_BLDC_TEMPERATURE = 20;
  SIGNAL_ID_ESC_TEMPERATURE = 21;
  SIGNAL_ID_BATTERY_TEMPERATURE = 22;
  SIGNAL_ID_AMBIENT_TEMPERATURE = 23;

  SIGNAL_ID_AMBIENT_HUMIDITY = 30;
  SIGNAL_ID_AMBIENT_PRESSURE = 31;

  SIGNAL_ID_BATTERY_SOC = 40;
}
