---
name: image
# on:
#   push:
#     # Pattern matched against refs/tags
#     tags:        
#       - 'v*'  
#     branches:
#       - master
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
    branches:
      - master



jobs:
  deploy:
    name: image build & push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Authenticate with ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ github.repository }}:latest,${{ github.repository }}:test
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
